const express = require('express');
const cors = require('cors');
const app = express();
const path = require('path');
const { default: mongoose } = require('mongoose');
const http = require('http');
const { Server: SocketIOServer } = require('socket.io');
const Class = require('./models/Class');
const Booking = require('./models/Booking');
const bcrypt = require('bcrypt');
const { hash } = require('crypto');
const jwt = require('jsonwebtoken');

const PORT = 8080;
const DATABASE_HOST = 'localhost';
const DATABASE_PORT = 27017;

//Basic Auth Values from Node environment variables
// const AUTH_USERNAME = process.env.AUTH_USERNAME;
// const AUTH_PASSWORD = process.env.AUTH_PASSWORD;
// const AUTH_TOKEN = process.env.AUTH_TOKEN;

//bycrpt values for Auth hashing of passwords
const saltRounds = 10;
//Access token secrets for JWT signing
//generated by running
// > node
// > require('crypto').randomBytes(64).toString('hex')
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const REFRESH_ACCESS_TOKEN = process.env.REFRESH_ACCESS_TOKEN;
//test admin user credentials
const testUserName1_Admin = "AdminUser1";
const test1PlaintTextPassword = "Ch@rliePapaS1erra630";
//test basix user credentials
const testUserName2_Basic = "BasicUser2";
const test2PlaintTextPassword = "TestPassword123";


// Create HTTP server and Socket.io instance
const server = http.createServer(app);
const io = new SocketIOServer(server, {
    cors: {
        origin: "*",
        methods: ["GET", "POST"]
    }
});

//Enable CORS for frontend requests
app.use(cors());

//database connect
const dbURL = `mongodb://${DATABASE_HOST}:${DATABASE_PORT}/class_schedule`;
mongoose.connect(dbURL);

const db = mongoose.connection;
const classesColl = db.collection("classes");
db.on('error', function (e) {
    console.log('error connecting:' + e);
});
db.on('open', function () {
    console.log('database connected!');
    addTestClassesToMongoDB();
});
//Add test passwords to db
addTestPasswordsToMongoDB();

//Socket.io Connection Handler
io.on('connection', (socket) => {
    console.log('New client connected:', socket.id);

    // Handle client sending a message
    socket.on('message', (data) => {
        console.log('Message received:', data);
        // Broadcast the message to all connected clients
        io.emit('message', data);
    });

    // Handle client disconnect
    socket.on('disconnect', () => {
        console.log('Client disconnected:', socket.id);
    });

    // Send welcome message to the connected client
    socket.emit('notification', {
        type: 'welcome',
        message: 'Welcome to the Community Class System! You are now connected.'
    });
});


// Sample classes to seed the database
// classCode is a unique numeric identifier, duration is stored in minutes
let class_schedule = [
    { classCode: 1001, hasImage: true, className: "Beginner Sewing", instructor: "Martha Collins", duration: 90, frequency: "Tue/Thu Jan 7 - Mar 27 2026", note: "" },
    { classCode: 1002, hasImage: true, className: "Cooking Lessons", instructor: "David Nguyen", duration: 120, frequency: "Wed Jan 8 - Apr 1 2026", note: "" },
    { classCode: 1003, hasImage: true, className: "Painting Lessons", instructor: "Sofia Reyes", duration: 90, frequency: "Sat Jan 10 - Mar 28 2026", note: "" },
    { classCode: 1004, hasImage: true, className: "Group Reading Circle", instructor: "James Okafor", duration: 60, frequency: "Mon Jan 6 - Apr 27 2026", note: "" },
    { classCode: 1005, hasImage: true, className: "Yoga for Seniors", instructor: "Linda Park", duration: 60, frequency: "Mon/Wed/Fri Jan 5 - Apr 24 2026", note: "" }
];

// Upsert seed classes — updates existing records so name/image fixes apply without clearing the DB
async function addTestClassesToMongoDB() {
    try {
        console.log('Syncing seed classes with database ...');

        const upsertPromises = class_schedule.map(classData =>
            Class.updateOne(
                { classCode: classData.classCode },   // match by code
                { $set: classData },                  // apply all fields
                { upsert: true }                      // insert if not found
            )
                .then(() => console.log('Synced class ' + classData.classCode + ': ' + classData.className))
                .catch(err => console.error('Error syncing class ' + classData.classCode + ': ' + err))
        );

        await Promise.all(upsertPromises);
        console.log('All seed classes synced successfully!');
    } catch (err) {
        console.error('Error in addTestClassesToMongoDB: ' + err);
    }
}

//Add testing passwords for bcrypt 
async function addTestPasswordsToMongoDB() {
    try {
        const hash1 = await bcrypt.hash(test1PlaintTextPassword, saltRounds);
        console.log(`Hash1: ${hash1}`);

        const res1 = await bcrypt.compare(test1PlaintTextPassword, hash1);
        console.log(`Pass1Test: ${res1}`);

        const hash2 = await bcrypt.hash(test2PlaintTextPassword, saltRounds);
        console.log(`Hash2: ${hash2}`);

        const res2 = await bcrypt.compare(test2PlaintTextPassword, hash2);
        console.log(`Pass2Test: ${res2}`);

        if (res1 && res2){
            console.log('Password hashing and validation working!')
        };

    } catch (err) {
        console.error('Error bcrypt creating or validating hash: ' + err);
    }


    
    // try {
    //     console.log('Syncing seed classes with database ...');

    //     const upsertPromises = class_schedule.map(classData =>
    //         Class.updateOne(
    //             { classCode: classData.classCode },   // match by code
    //             { $set: classData },                  // apply all fields
    //             { upsert: true }                      // insert if not found
    //         )
    //             .then(() => console.log('Synced class ' + classData.classCode + ': ' + classData.className))
    //             .catch(err => console.error('Error syncing class ' + classData.classCode + ': ' + err))
    //     );

    //     await Promise.all(upsertPromises);
    //     console.log('All seed classes synced successfully!');
    // } catch (err) {
    //     console.error('Error in addTestClassesToMongoDB: ' + err);
    // }
}

function requireAuth(req, res, next) {
    const authHeader = req.headers.authorization;

    //we are expecting the auth header to be in the format "Bearer <token>", so we check for that and extract the token
    //"Bearer " is part of the HTTP standard for authorization headers and indicates that the client is sending a token for authentication.
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        return res.status(401).json({ error: 'Authorization header missing or invalid' });
    }

    const token = authHeader.split(' ')[1]; //split token at first space since everthing after is the token "Bearer <token>"
    jwt.verify(token, ACCESS_TOKEN_SECRET, (err, user) => {
        if (err) return res.sendStatus(403)
        req.user = user
        next()
    })
    // if (token !== AUTH_TOKEN) {
    //     return res.status(401).json({ error: 'Invalid auth token' });
    // }
}

/*************************************************/
/********* Defining (CRUD) API routes ************/
/*************************************************/

/************************/
/******* SERVER *********/
/******* AUTH ***********/
/************************/
//Simple login route that returns a static demo token
app.post('/api/auth/login', express.json(), (req, res) => {
    const { username, password } = req.body || {};

    if (!username || !password) {
        return res.status(400).json({ error: 'Username and password are required' });
    }

    //Login check for test admin user
    if (username === testUserName1_Admin && password === test1PlaintTextPassword) {
        //User data for JWT token
        const user = {
            name: username,
            permission: 'admin'
        };
        //Sign/create JWT token with secret from .env
        const ACCESS_TOKEN = jwt.sign(user, ACCESS_TOKEN_SECRET);

        return res.status(200).json({
            message: 'Login successful',
            token: ACCESS_TOKEN
        });
    }
    //Login check for test basic user
    else if (username === testUserName2_Basic && password === test2PlaintTextPassword) {
        //User data for JWT token
        const user = {
            name: username,
            permission: 'basic'
        };
        //Sign/create JWT token with secret from .env
        const ACCESS_TOKEN = jwt.sign(user, ACCESS_TOKEN_SECRET);

        return res.status(200).json({
            message: 'Login successful',
            token: ACCESS_TOKEN
        });
    }

    return res.status(401).json({ error: 'Invalid username or password' });
});

/************************/
/******* SERVER *********/
/******** READ **********/
/************************/
//get all classes
app.get('/api/classes', async (req, res) => {
    try {
        const classes = await Class.find();
        res.json(classes);
        console.log('Retrieved ' + classes.length + ' classes from database');
    } catch (err) {
        res.status(500).json({ error: 'Error retrieving classes: ' + err });
    }
});

/************************/
/******* SERVER *********/
/******** READ **********/
/************************/
//get class by class code (unique id)
//In Express.js route definitions, the colon (:) prefix indicates a route parameter (also called a path parameter)
app.get('/api/classes/code/:code', async (req, res) => {
    try {
        //convert class code to number to match the database type
        const classCode = Number(req.params.code);
        //findOne() returns the first matching document (or null if none found)
        const foundClass = await Class.findOne({ classCode: classCode });
        if (foundClass) {
            res.status(200).json(foundClass); //status code 200 = OK
        } else {
            res.status(404).json({ error: "Class not found" });  //status 404 code = NOT FOUND
        }
    } catch (err) {
        res.status(500).json({ error: 'Error retrieving class: ' + err });
    }
});

/************************/
/******* SERVER *********/
/******** READ **********/
/************************/
//return a json object with all classes that match the search criteria
//Enhanced search: supports partial matching by instructor, classCode, or duration
//Using query parameters: /api/classes/search?instructor=Name&classCode=123&duration=90
app.get('/api/classes/search', async (req, res) => {
    try {
        const { instructor, classCode, duration } = req.query;

        // At least one search parameter must be provided
        if (!instructor && !classCode && !duration) {
            return res.status(400).json({ error: "Please provide at least one search parameter (instructor, classCode, or duration)" });
        }

        // Build dynamic filter using regex for partial, case-insensitive matching
        const classFilter = {};

        if (instructor) {
            // Partial match, case-insensitive
            classFilter.instructor = { $regex: instructor, $options: 'i' };
        }

        if (classCode) {

            const codeNum = parseInt(classCode);
            if (!isNaN(codeNum)) {
                classFilter.classCode = codeNum;
            }
        }

        if (duration) {
            // Exact duration match (in minutes)
            classFilter.duration = parseInt(duration);
        }

        const classes = await classesColl.find(classFilter).toArray();
        if (classes.length > 0) {
            res.status(200).json(classes);
        } else {
            res.status(404).json({ error: "No classes found matching your search criteria" });
        }
    } catch (err) {
        res.status(500).json({ error: 'Error searching classes: ' + err });
    }
});

/************************/
/******* SERVER *********/
/******* CREATE *********/
/************************/
//create new class
app.post('/api/classes', requireAuth, express.json(), async (req, res) => {
    try {
        const newClassData = req.body;
        if (newClassData && newClassData.className && newClassData.instructor && newClassData.duration && newClassData.frequency) {

            if (!newClassData.hasImage) {
                newClassData.hasImage = false; //default value
            }

            const newClass = new Class(newClassData);
            const savedClass = await newClass.save();

            // Emit real-time notification to all connected clients
            io.emit('class_created', {
                type: 'class_added',
                message: `New class added: "${savedClass.className}" by ${savedClass.instructor}`,
                class: savedClass
            });

            res.status(201).json(savedClass);
        } else {
            res.status(400).json({ error: "Invalid class data" });
        }
    } catch (err) {
        res.status(500).json({ error: 'Error creating class: ' + err });
    }
});

/************************/
/******* SERVER *********/
/******* UPDATE *********/
/************************/
//update class by class code (unique)
app.patch('/api/classes/code/:code', requireAuth, express.json(), async (req, res) => {
    try {
        console.log("PATCH request received");

        const classCode = Number(req.params.code);
        const classFilter = { classCode: classCode };

        const newNote = req.body.note;
        const updateNote = {
            $set: {
                note: newNote
            },
        };

        const result = await classesColl.updateOne(classFilter, updateNote);
        if (result) {
            // Emit real-time notification to all connected clients
            io.emit('class_updated', {
                type: 'class_modified',
                message: `Class with code ${classCode} has been updated`,
                classCode: classCode,
                note: newNote
            });

            res.status(200).json(result);
        } else {
            res.status(404).json({ error: "Class not found" });
        }
    } catch (err) {
        res.status(500).json({ error: 'Error updating class: ' + err });
    }
});

/************************/
/******* SERVER *********/
/******* DELETE *********/
/************************/
//delete by unique id, i.e., class code (can only delete one)
app.delete('/api/classes/code/:code', requireAuth, async (req, res) => {
    try {
        const classCode = Number(req.params.code);
        const classFilter = { classCode: classCode };

        const result = classesColl.deleteOne(classFilter);
        if (result) {
            // Emit real-time notification to all connected clients
            io.emit('class_deleted', {
                type: 'class_removed',
                message: `Class with code ${classCode} has been deleted`,
                classCode: classCode
            });

            res.status(204).send();
        } else {
            res.status(404).json({ error: "Class not found" });
        }
    } catch (err) {
        res.status(500).json({ error: 'Error deleting class: ' + err });
    }
});

/************************/
/******* SERVER *********/
/****** BOOKINGS ********/
/************************/
// Get all bookings, joined with class details
app.get('/api/bookings', async (req, res) => {
    try {
        const bookings = await Booking.find();

        // Enrich each booking with the matching class document
        const enriched = await Promise.all(
            bookings.map(async (b) => {
                const cls = await Class.findOne({ classCode: b.classCode });
                return { ...b.toObject(), classDetails: cls };
            })
        );

        res.status(200).json(enriched);
    } catch (err) {
        res.status(500).json({ error: 'Error retrieving bookings: ' + err });
    }
});

// Book a class (requires auth)
app.post('/api/bookings', requireAuth, express.json(), async (req, res) => {
    try {
        const { classCode } = req.body;

        if (!classCode) {
            return res.status(400).json({ error: 'classCode is required' });
        }

        // Make sure the class exists
        const cls = await Class.findOne({ classCode: Number(classCode) });
        if (!cls) {
            return res.status(404).json({ error: 'Class not found' });
        }

        // Prevent duplicate bookings
        const existing = await Booking.findOne({ classCode: Number(classCode) });
        if (existing) {
            return res.status(409).json({ error: 'This class is already booked.' });
        }

        // Create booking
        const newBooking = new Booking({ classCode: Number(classCode) });
        const savedBooking = await newBooking.save();

        // Emit real time notification to all connected clients
        io.emit('class_booked', {
            type: 'class_booked',
            message: `"${cls.className}" has been successfully booked!`,
            classCode: cls.classCode,
            className: cls.className
        });

        res.status(201).json(savedBooking);
    } catch (err) {
        res.status(500).json({ error: 'Error booking class: ' + err });
    }
});

// Cancel a booking by classCode (requires auth)
app.delete('/api/bookings/:classCode', requireAuth, async (req, res) => {
    try {
        const classCode = Number(req.params.classCode);

        // Look up class name for the notification message
        const cls = await Class.findOne({ classCode });
        const className = cls ? cls.className : `Class ${classCode}`;

        await Booking.deleteOne({ classCode });

        io.emit('class_booking_cancelled', {
            type: 'class_booking_cancelled',
            message: `Booking for "${className}" has been cancelled.`,
            classCode
        });

        res.status(204).send();
    } catch (err) {
        res.status(500).json({ error: 'Error cancelling booking: ' + err });
    }
});

//starts server
server.listen(PORT, () => { console.log("Server started on port: " + PORT) });